apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-strawberry.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rag-strawberry.labels" . | nindent 4 }}
data:
  rag_server.py: |-
{{ .Files.Get "files/rag_server.py" | indent 4 }}
